<?php


 function autoload_d1d9beb01f52a0e991540aca7e55aa2b($class)
{
    $classes = array(
        'AppBundle\Service\WsAfip\Service' => __DIR__ .'/Service.php',
        'AppBundle\Service\WsAfip\FECAESolicitar' => __DIR__ .'/FECAESolicitar.php',
        'AppBundle\Service\WsAfip\FEAuthRequest' => __DIR__ .'/FEAuthRequest.php',
        'AppBundle\Service\WsAfip\FECAERequest' => __DIR__ .'/FECAERequest.php',
        'AppBundle\Service\WsAfip\FECAECabRequest' => __DIR__ .'/FECAECabRequest.php',
        'AppBundle\Service\WsAfip\FECabRequest' => __DIR__ .'/FECabRequest.php',
        'AppBundle\Service\WsAfip\ArrayOfFECAEDetRequest' => __DIR__ .'/ArrayOfFECAEDetRequest.php',
        'AppBundle\Service\WsAfip\FECAEDetRequest' => __DIR__ .'/FECAEDetRequest.php',
        'AppBundle\Service\WsAfip\FEDetRequest' => __DIR__ .'/FEDetRequest.php',
        'AppBundle\Service\WsAfip\ArrayOfCbteAsoc' => __DIR__ .'/ArrayOfCbteAsoc.php',
        'AppBundle\Service\WsAfip\CbteAsoc' => __DIR__ .'/CbteAsoc.php',
        'AppBundle\Service\WsAfip\ArrayOfTributo' => __DIR__ .'/ArrayOfTributo.php',
        'AppBundle\Service\WsAfip\Tributo' => __DIR__ .'/Tributo.php',
        'AppBundle\Service\WsAfip\ArrayOfAlicIva' => __DIR__ .'/ArrayOfAlicIva.php',
        'AppBundle\Service\WsAfip\AlicIva' => __DIR__ .'/AlicIva.php',
        'AppBundle\Service\WsAfip\ArrayOfOpcional' => __DIR__ .'/ArrayOfOpcional.php',
        'AppBundle\Service\WsAfip\Opcional' => __DIR__ .'/Opcional.php',
        'AppBundle\Service\WsAfip\FECAESolicitarResponse' => __DIR__ .'/FECAESolicitarResponse.php',
        'AppBundle\Service\WsAfip\FECAEResponse' => __DIR__ .'/FECAEResponse.php',
        'AppBundle\Service\WsAfip\FECAECabResponse' => __DIR__ .'/FECAECabResponse.php',
        'AppBundle\Service\WsAfip\FECabResponse' => __DIR__ .'/FECabResponse.php',
        'AppBundle\Service\WsAfip\ArrayOfFECAEDetResponse' => __DIR__ .'/ArrayOfFECAEDetResponse.php',
        'AppBundle\Service\WsAfip\FECAEDetResponse' => __DIR__ .'/FECAEDetResponse.php',
        'AppBundle\Service\WsAfip\FEDetResponse' => __DIR__ .'/FEDetResponse.php',
        'AppBundle\Service\WsAfip\ArrayOfObs' => __DIR__ .'/ArrayOfObs.php',
        'AppBundle\Service\WsAfip\Obs' => __DIR__ .'/Obs.php',
        'AppBundle\Service\WsAfip\ArrayOfEvt' => __DIR__ .'/ArrayOfEvt.php',
        'AppBundle\Service\WsAfip\Evt' => __DIR__ .'/Evt.php',
        'AppBundle\Service\WsAfip\ArrayOfErr' => __DIR__ .'/ArrayOfErr.php',
        'AppBundle\Service\WsAfip\Err' => __DIR__ .'/Err.php',
        'AppBundle\Service\WsAfip\FECompTotXRequest' => __DIR__ .'/FECompTotXRequest.php',
        'AppBundle\Service\WsAfip\FECompTotXRequestResponse' => __DIR__ .'/FECompTotXRequestResponse.php',
        'AppBundle\Service\WsAfip\FERegXReqResponse' => __DIR__ .'/FERegXReqResponse.php',
        'AppBundle\Service\WsAfip\FEDummy' => __DIR__ .'/FEDummy.php',
        'AppBundle\Service\WsAfip\FEDummyResponse' => __DIR__ .'/FEDummyResponse.php',
        'AppBundle\Service\WsAfip\DummyResponse' => __DIR__ .'/DummyResponse.php',
        'AppBundle\Service\WsAfip\FECompUltimoAutorizado' => __DIR__ .'/FECompUltimoAutorizado.php',
        'AppBundle\Service\WsAfip\FECompUltimoAutorizadoResponse' => __DIR__ .'/FECompUltimoAutorizadoResponse.php',
        'AppBundle\Service\WsAfip\FERecuperaLastCbteResponse' => __DIR__ .'/FERecuperaLastCbteResponse.php',
        'AppBundle\Service\WsAfip\FECompConsultar' => __DIR__ .'/FECompConsultar.php',
        'AppBundle\Service\WsAfip\FECompConsultaReq' => __DIR__ .'/FECompConsultaReq.php',
        'AppBundle\Service\WsAfip\FECompConsultarResponse' => __DIR__ .'/FECompConsultarResponse.php',
        'AppBundle\Service\WsAfip\FECompConsultaResponse' => __DIR__ .'/FECompConsultaResponse.php',
        'AppBundle\Service\WsAfip\FECompConsResponse' => __DIR__ .'/FECompConsResponse.php',
        'AppBundle\Service\WsAfip\FECAEARegInformativo' => __DIR__ .'/FECAEARegInformativo.php',
        'AppBundle\Service\WsAfip\FECAEARequest' => __DIR__ .'/FECAEARequest.php',
        'AppBundle\Service\WsAfip\FECAEACabRequest' => __DIR__ .'/FECAEACabRequest.php',
        'AppBundle\Service\WsAfip\ArrayOfFECAEADetRequest' => __DIR__ .'/ArrayOfFECAEADetRequest.php',
        'AppBundle\Service\WsAfip\FECAEADetRequest' => __DIR__ .'/FECAEADetRequest.php',
        'AppBundle\Service\WsAfip\FECAEARegInformativoResponse' => __DIR__ .'/FECAEARegInformativoResponse.php',
        'AppBundle\Service\WsAfip\FECAEAResponse' => __DIR__ .'/FECAEAResponse.php',
        'AppBundle\Service\WsAfip\FECAEACabResponse' => __DIR__ .'/FECAEACabResponse.php',
        'AppBundle\Service\WsAfip\ArrayOfFECAEADetResponse' => __DIR__ .'/ArrayOfFECAEADetResponse.php',
        'AppBundle\Service\WsAfip\FECAEADetResponse' => __DIR__ .'/FECAEADetResponse.php',
        'AppBundle\Service\WsAfip\FECAEASolicitar' => __DIR__ .'/FECAEASolicitar.php',
        'AppBundle\Service\WsAfip\FECAEASolicitarResponse' => __DIR__ .'/FECAEASolicitarResponse.php',
        'AppBundle\Service\WsAfip\FECAEAGetResponse' => __DIR__ .'/FECAEAGetResponse.php',
        'AppBundle\Service\WsAfip\FECAEAGet' => __DIR__ .'/FECAEAGet.php',
        'AppBundle\Service\WsAfip\FECAEASinMovimientoConsultar' => __DIR__ .'/FECAEASinMovimientoConsultar.php',
        'AppBundle\Service\WsAfip\FECAEASinMovimientoConsultarResponse' => __DIR__ .'/FECAEASinMovimientoConsultarResponse.php',
        'AppBundle\Service\WsAfip\FECAEASinMovConsResponse' => __DIR__ .'/FECAEASinMovConsResponse.php',
        'AppBundle\Service\WsAfip\ArrayOfFECAEASinMov' => __DIR__ .'/ArrayOfFECAEASinMov.php',
        'AppBundle\Service\WsAfip\FECAEASinMov' => __DIR__ .'/FECAEASinMov.php',
        'AppBundle\Service\WsAfip\FECAEASinMovimientoInformar' => __DIR__ .'/FECAEASinMovimientoInformar.php',
        'AppBundle\Service\WsAfip\FECAEASinMovimientoInformarResponse' => __DIR__ .'/FECAEASinMovimientoInformarResponse.php',
        'AppBundle\Service\WsAfip\FECAEASinMovResponse' => __DIR__ .'/FECAEASinMovResponse.php',
        'AppBundle\Service\WsAfip\FECAEAConsultar' => __DIR__ .'/FECAEAConsultar.php',
        'AppBundle\Service\WsAfip\FECAEAConsultarResponse' => __DIR__ .'/FECAEAConsultarResponse.php',
        'AppBundle\Service\WsAfip\FEParamGetCotizacion' => __DIR__ .'/FEParamGetCotizacion.php',
        'AppBundle\Service\WsAfip\FEParamGetCotizacionResponse' => __DIR__ .'/FEParamGetCotizacionResponse.php',
        'AppBundle\Service\WsAfip\FECotizacionResponse' => __DIR__ .'/FECotizacionResponse.php',
        'AppBundle\Service\WsAfip\Cotizacion' => __DIR__ .'/Cotizacion.php',
        'AppBundle\Service\WsAfip\FEParamGetTiposTributos' => __DIR__ .'/FEParamGetTiposTributos.php',
        'AppBundle\Service\WsAfip\FEParamGetTiposTributosResponse' => __DIR__ .'/FEParamGetTiposTributosResponse.php',
        'AppBundle\Service\WsAfip\FETributoResponse' => __DIR__ .'/FETributoResponse.php',
        'AppBundle\Service\WsAfip\ArrayOfTributoTipo' => __DIR__ .'/ArrayOfTributoTipo.php',
        'AppBundle\Service\WsAfip\TributoTipo' => __DIR__ .'/TributoTipo.php',
        'AppBundle\Service\WsAfip\FEParamGetTiposMonedas' => __DIR__ .'/FEParamGetTiposMonedas.php',
        'AppBundle\Service\WsAfip\FEParamGetTiposMonedasResponse' => __DIR__ .'/FEParamGetTiposMonedasResponse.php',
        'AppBundle\Service\WsAfip\MonedaResponse' => __DIR__ .'/MonedaResponse.php',
        'AppBundle\Service\WsAfip\ArrayOfMoneda' => __DIR__ .'/ArrayOfMoneda.php',
        'AppBundle\Service\WsAfip\Moneda' => __DIR__ .'/Moneda.php',
        'AppBundle\Service\WsAfip\FEParamGetTiposIva' => __DIR__ .'/FEParamGetTiposIva.php',
        'AppBundle\Service\WsAfip\FEParamGetTiposIvaResponse' => __DIR__ .'/FEParamGetTiposIvaResponse.php',
        'AppBundle\Service\WsAfip\IvaTipoResponse' => __DIR__ .'/IvaTipoResponse.php',
        'AppBundle\Service\WsAfip\ArrayOfIvaTipo' => __DIR__ .'/ArrayOfIvaTipo.php',
        'AppBundle\Service\WsAfip\IvaTipo' => __DIR__ .'/IvaTipo.php',
        'AppBundle\Service\WsAfip\FEParamGetTiposOpcional' => __DIR__ .'/FEParamGetTiposOpcional.php',
        'AppBundle\Service\WsAfip\FEParamGetTiposOpcionalResponse' => __DIR__ .'/FEParamGetTiposOpcionalResponse.php',
        'AppBundle\Service\WsAfip\OpcionalTipoResponse' => __DIR__ .'/OpcionalTipoResponse.php',
        'AppBundle\Service\WsAfip\ArrayOfOpcionalTipo' => __DIR__ .'/ArrayOfOpcionalTipo.php',
        'AppBundle\Service\WsAfip\OpcionalTipo' => __DIR__ .'/OpcionalTipo.php',
        'AppBundle\Service\WsAfip\FEParamGetTiposConcepto' => __DIR__ .'/FEParamGetTiposConcepto.php',
        'AppBundle\Service\WsAfip\FEParamGetTiposConceptoResponse' => __DIR__ .'/FEParamGetTiposConceptoResponse.php',
        'AppBundle\Service\WsAfip\ConceptoTipoResponse' => __DIR__ .'/ConceptoTipoResponse.php',
        'AppBundle\Service\WsAfip\ArrayOfConceptoTipo' => __DIR__ .'/ArrayOfConceptoTipo.php',
        'AppBundle\Service\WsAfip\ConceptoTipo' => __DIR__ .'/ConceptoTipo.php',
        'AppBundle\Service\WsAfip\FEParamGetPtosVenta' => __DIR__ .'/FEParamGetPtosVenta.php',
        'AppBundle\Service\WsAfip\FEParamGetPtosVentaResponse' => __DIR__ .'/FEParamGetPtosVentaResponse.php',
        'AppBundle\Service\WsAfip\FEPtoVentaResponse' => __DIR__ .'/FEPtoVentaResponse.php',
        'AppBundle\Service\WsAfip\ArrayOfPtoVenta' => __DIR__ .'/ArrayOfPtoVenta.php',
        'AppBundle\Service\WsAfip\PtoVenta' => __DIR__ .'/PtoVenta.php',
        'AppBundle\Service\WsAfip\FEParamGetTiposCbte' => __DIR__ .'/FEParamGetTiposCbte.php',
        'AppBundle\Service\WsAfip\FEParamGetTiposCbteResponse' => __DIR__ .'/FEParamGetTiposCbteResponse.php',
        'AppBundle\Service\WsAfip\CbteTipoResponse' => __DIR__ .'/CbteTipoResponse.php',
        'AppBundle\Service\WsAfip\ArrayOfCbteTipo' => __DIR__ .'/ArrayOfCbteTipo.php',
        'AppBundle\Service\WsAfip\CbteTipo' => __DIR__ .'/CbteTipo.php',
        'AppBundle\Service\WsAfip\FEParamGetTiposDoc' => __DIR__ .'/FEParamGetTiposDoc.php',
        'AppBundle\Service\WsAfip\FEParamGetTiposDocResponse' => __DIR__ .'/FEParamGetTiposDocResponse.php',
        'AppBundle\Service\WsAfip\DocTipoResponse' => __DIR__ .'/DocTipoResponse.php',
        'AppBundle\Service\WsAfip\ArrayOfDocTipo' => __DIR__ .'/ArrayOfDocTipo.php',
        'AppBundle\Service\WsAfip\DocTipo' => __DIR__ .'/DocTipo.php',
        'AppBundle\Service\WsAfip\FEParamGetTiposPaises' => __DIR__ .'/FEParamGetTiposPaises.php',
        'AppBundle\Service\WsAfip\FEParamGetTiposPaisesResponse' => __DIR__ .'/FEParamGetTiposPaisesResponse.php',
        'AppBundle\Service\WsAfip\FEPaisResponse' => __DIR__ .'/FEPaisResponse.php',
        'AppBundle\Service\WsAfip\ArrayOfPaisTipo' => __DIR__ .'/ArrayOfPaisTipo.php',
        'AppBundle\Service\WsAfip\PaisTipo' => __DIR__ .'/PaisTipo.php'
    );
    if (!empty($classes[$class])) {
        include $classes[$class];
    };
}

spl_autoload_register('autoload_d1d9beb01f52a0e991540aca7e55aa2b');

// Do nothing. The rest is just leftovers from the code generation.
{
}
