<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;


/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NumeroComprobanteRepository extends EntityRepository
{
    public function findLastNumeroComprobante($idPuntoVenta)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT c'
                . ' FROM AppBundle:NumeroComprobante c '
                . ' WHERE c.puntoVenta = :punto'
                . ' ORDER BY c.id DESC'
            )
            ->setParameter('punto', $idPuntoVenta)
            ->setMaxResults(1)
            ->getResult();
    }


}
